apiVersion: v2
name: github-provider
description: Krateo PlatformOps Github Provider
type: application
icon: "https://github.com/projectkerberus/kerberus-dashboard/blob/main/docs/media/square_black_logo.png"

version: VERSION
appVersion: VERSION

dependencies:
  - name: helm-chart-library
    version: 0.1.3
    repository: http://charts.krateo.io